version: "3"

services:
  chatbot_parser:
    build: ./chatbot_parser
    ports:
      - "5050:5050"
    depends_on:
      - postgres_container
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=postgres_container
      - DB_NAME=chatbot
    volumes:
      - ./chatbot_parser:/usr/src/app
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  shrug_command:
    build: ./shrug_command
    ports:
      - "8080:8080