# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip3 install -r requirements.txt

# Copy source code
COPY chatbot_parser.py .

# Expose port 5050
EXPOSE 5050

# Run the application
CMD ["python3", "chatbot_parser.py"]
