# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip3 install -r requirements.txt

# Copy source code
COPY shrug_command_server.py .

# Expose port 5000
EXPOSE 5000

# Run the application
CMD ["python3", "shrug_command_server.py"]
